<?php $this->headMeta()->appendName('keywords', 'games, code, javascript'); ?>
<?php $this->headMeta()->appendName('description', 'Games and Code: features javascript games and code developed by Richard Lawson.'); ?>
<?php $this->headTitle()->append('Games and Code'); ?>
 
<?php $this->headLink()->appendStylesheet('/f-14-fighter/css/main.css'); ?>
<?php $this->headLink()->appendStylesheet('/f-14-fighter/css/background.css'); ?>
<?php $this->headLink()->appendStylesheet('/f-14-fighter/css/sprites.css'); ?>

<?php $this->headScript()->appendFile('/js/jquery/jquery.text-effects.js'); ?>

<?php $this->headScript()->appendFile('/f-14-fighter/js/GameController.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/Canvas.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/Rectangle.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/GameObject.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/MovingGameObject.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/RepeatingBackground.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/Ship.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/Rocket.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/EnemyFactory.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/Enemy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/EnemyRocket.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/MoveStrategy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/SimpleMoveLeftStrategy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/SimpleMoveRightStrategy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/SimpleUpDownMoveStrategy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/NoseDiveMoveStrategy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/SmartMoveStrategy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/SmartEnemy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/BossEnemy.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/InnerBoundaryChecker.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/OutterBoundaryChecker.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/BoundaryCleaner.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/SimpleCollection.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/MovingGameObjectCollection.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/EnemyCollection.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/ScoreManager.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/ImagePreLoader.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/CollisionDetector.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/ScreenBuilder.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/CommunicationPopUp.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/Dashboard.js'); ?>
<?php $this->headScript()->appendFile('/f-14-fighter/js/Util.js'); ?>
<?php $this->headScript()->captureStart() ?>
	$(function(){
		var gameController = new GameController();
		gameController.init();
		$("#start-button").click(function(event){
			event.preventDefault();
			gameController.startGame();
			$("#intro-screen").remove();
		});	
		
	});
<?php $this->headScript()->captureEnd() ?>
<h1>Welcome</h1>
<p>I decided that it was about time that I had my own website, so eventually got round to setting up a server on Amazon's AWS platform and adding a couple of pages. To get the ball rolling, I've added a JavaScript game that I built about a month ago (more info below). I'm also planning on sharing some stories about coding and maybe posting the odd tutorial in the coming months.</p>
<h1>F-14 Fighter</h1>
<p>On my CV I mention something about advanced JavaScript; however, my js skills had become a bit rusty over the last year, especially when it came to OO js. So, I decided to build a js game, F-14 Fighter, in the hope that it would refresh my knowledge. I'm planning on writing a tutorial about how to build a js game in the near future (I'll use F-14 Fighter as the example), but until then you can always check out the <a href="https://github.com/richardlawson/f-14-fighter" target="_blank">source code</a> on github.</p>
<br class="floatfix"/>
<div id="canvas">
	<div id="preloader">
		<div id="progress-bar-text">Loading ...</div>
		<div id="progress-bar-holder">
			<div id="progress-bar"><!-- --></div>
		</div>
	</div>
	<div id="intro-screen">
		<div>
			<a href="" id="start-button">Play</a>
		</div>
	</div>
	<div id="info-screen">
		<!-- -->
	</div>
	<div id="mission-panel">
		<!-- -->
	</div>
</div>
<br class="floatfix"/>
<h1>F-14 Fighter goes Facebook</h1>
<p>I thought that it would be nice to allow players of F-14 Fighter to compare scores with friends, so created a facebook app to make this possible. I used Facebook's PHP SDK to handle logging in to the app and gathering player info. AJAX is used to send score data to the server, which means that game play isn't interrupted with page refreshes.</p>
<p>I didn't think there would be a great deal of PHP code to handle the scoring, so, to make things more interesting, decided to use Doctrine to handle my DB code. Integrating Doctrine with the ZendFramework was a bit of a pain, but once it was up and running seemed like a pretty good way to go. I think that I probably ended up writing about 50% less code than I would of done if I had stuck to the more traditional Data Mapper and Zend Table approach. I also put PHPUnit's DB Extension to good use on the testing front, which worked almost seamlessly with the doctrine code.</p>
<p>You can check out the F-14 Fighter Facebook app at <a href="http://apps.facebook.com/tomcat-fighter" target="_blank">http://apps.facebook.com/tomcat-fighter</a>. I've also uploaded the <a href="https://github.com/richardlawson/gamesandcode" target="_blank">source code</a> for gamesandcode.co.uk to github, which includes the score handling for F-14 Fighter. Most of that code can be found in the application/controllers/FacebookController.php file and the library/GC/Entity folder.   
	