<?php echo $this->doctype() ?>
<html lang="en">
<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
	  <?php $this->headLink()->prependStylesheet('/css/main.css'); ?>
	  <?php $this->headScript()->prependFile('/js/jquery/jquery-1.4.2.js'); ?>
	  <?php $this->headScript()->appendFile('/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9' )); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headScript(); ?>
</head>
<body>
	<div id="wrapper">
		<?php echo $this->render('_header.phtml'); ?>
		<!-- main content -->
		<div id="content">
		   <?php echo $this->layout()->content ?>
		</div>
		<?php echo $this->render('_footer.phtml'); ?>
	</div>
</body>
</html>